### ISSUE TITLE
A very high level course path for each program can be added

### ISSUE THREAD

**Issue by hvsharma** [fcc-hyd/month-of-code#5]
Adding a course path will provide a concrete road-map for both attendees and mentors.

**Comment by vramana** [comment]
@duttakapil  said he doesn't want to put it up publicly because he wanted it to be exclusive to the people who are selected.

**Comment by duttakapil** [comment]
@hvsharma we do have a high level concrete road-map for each of the domains, but we're only making it accessible to the students who get accepted into the program, at least for the moment.

**Comment by hvsharma** [comment]
Okay... That's great!
